a = float(input("Enter a value: "))
b = float(input("Enter b value: "))
print(f"The sum of {a} and {b} is {a+b}.")
print(f"The difference of {a} and {b} is {a-b}.")
print(f"The product of {a} and {b} is {a*b}.")
print(f"The quotient of {a} and {b} is {a/b}.")